/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  onboarding: [
    // === Top Section ===
    {
      type: "doc",
      label: "Home",
      id: "0 0 Home",
    },
    {
      type: "doc",
      label: "Platform Overview",
      id: "0 1 Platform Overview",
    },
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "getting-started",
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "guides",
        },
      ],
    },
    {
      type: "category",
      label: "Authentication",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "authentication",
        },
      ],
    },
    // === Payments ===

    // {
    //   type: "doc",
    //   label: "Access Passes",
    //   id: "payments.access-passes",
    // },
    // {
    //   type: "doc",
    //   label: "Plans",
    //   id: "payments.plans",
    // },
    // {
    //   type: "doc",
    //   label: "Memberships",
    //   id: "users.memberships",
    // },
    // {
    //   type: "doc",
    //   label: "Engagement",
    //   id: "users.engagement",
    // },
    // {
    //   type: "doc",
    //   label: "Member Information",
    //   id: "users.member-information",
    // },
    // {
    //   type: "doc",
    //   label: "Payments",
    //   id: "users.payments",
    // },
    // {
    //   type: "doc",
    //   label: "Experiences",
    //   id: "users.experiences",
    // },

    // // === Deploy Contracts ===
    // {
    //   type: "doc",
    //   label: "Release",
    //   id: "6 2 Releasing your contract",
    // },
    // {
    //   type: "doc",
    //   label: "Deploy",
    //   id: "6 3 Deploying your contract",
    // },
    // {
    //   type: "link",
    //   label: "Prebuilt Contracts",
    //   href: "/pre-built-contracts",
    // },

    // === Discoverability ===
    // === Manage Projects ===
    // === Bottom Section ===
    {
      type: "doc",
      label: "Webhooks",
      id: "webhooks",
    },
    {
      type: "category",
      label: "Templates",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "templates",
        },
      ],
    },

    {
      type: "link",
      label: "API Reference",
      href: "https://dev.whop.com/",
    },
    {
      type: "category",
      label: "SDK References",
      className: "bottom-menu-group",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "link",
          label: "JavaScript / TypeScript",
          href: "/typescript",
        },
        {
          type: "link",
          label: "React",
          href: "/react",
        },
        {
          type: "link",
          label: "Python",
          href: "/python",
        },
        {
          type: "link",
          label: "Go",
          href: "/go",
        },
      ],
    },
  ],

  buildContracts: [
    {
      type: "autogenerated",
      dirName: "4 Contracts SDK",
    },
  ],

  prebuiltContracts: [
    {
      type: "autogenerated",
      dirName: "1 Pre-Built Contracts",
    },
  ],

  sdk: [
    {
      type: "autogenerated",
      dirName: "3 Web3 SDK",
    },
  ],

  storage: [
    {
      type: "autogenerated",
      dirName: "6 Storage",
    },
  ],

  solana: [
    {
      type: "autogenerated",
      dirName: "8 Solana",
    },
  ],

  "ui-components": [
    {
      type: "autogenerated",
      dirName: "3 UI Components",
    },
  ],
};

module.exports = sidebars;
